fix: Remove references to non-existent avatar_url column in migration
The users table does not have an avatar_url column. This commit fixes
the SQL migration script by replacing references to avatar_url with
NULL values in:
- get_user_conversations() function (line 300)
- direct_messages_complete view (lines 410-411)

This resolves the error:
ERROR: column sender.avatar_url does not exist
LINE 410: ...as sender_id, sender.nickname as sender_nickname, sender.ava...

Fixes #issue-with-migration-errors